services:
  app:
    build:
      context: .
      dockerfile: ".docker/ruby/Dockerfile"
    container_name: grpc-client
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: bash -lc "bundle install && bundle exec rails s -b 0.0.0.0 -p 3000"